[package]
name = "news"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.12", features = ["blocking"] }
rss = "2.0.12"
tokio={version="1.44.0",features=["full"]}
thiserror={version="2.0.12"}
